apiVersion: v1
kind: Service
metadata:
  name: {{ include "compteurs-velo.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    {{- include "compteurs-velo.selectorLabels" . | nindent 4 }}
